// --------------------(1variant)------------------------------
// "use client";

// import { Metadata } from "next";

// import { getAllPosts } from "@/servises/getPosts";
// import { useEffect, useState } from "react";

// import LoadingPosts from "./loading";
// import { Posts } from "@/components/Posts";
// import { PostSearch } from "@/components/PostSearch";

// export const metadata: Metadata = {
//   title: "Blog | Blog App",
//   description: "Generated by create next app",
// };

// export default async function Blog() {
//   const [posts, setPosts] = useState<any[]>([]);
//   const [loading, setLoading] = useState(true);

//   useEffect(() => {
//     getAllPosts()
//       .then(setPosts)
//       .finally(() => setLoading(false));
//   }, []);

//   return (
//     <>
//       <h1>Blog page</h1>
//       <PostSearch onSearch={setPosts} />
//       {loading ? (
//         // <h3>Loading...</h3>
//         <LoadingPosts />
//       ) : (
//         <Posts posts={posts} />
//       )}
//     </>
//   );
// }

// ---------------------------(2variant)------------------------------------
"use client";

import { Metadata } from "next";
import { Posts } from "@/components/Posts";
import { PostSearch } from "@/components/PostSearch";

export const metadata: Metadata = {
  title: "Blog | Blog App",
  description: "Generated by create next app",
};

export default async function Blog() {
  return (
    <>
      <h1>Blog page</h1>
      <PostSearch />
      <Posts />
    </>
  );
}
// -----------------------------------------------------------------------------
